---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Check nginx binary
    stat:
      path: "/usr/sbin/nginx"
      register: this
      failed_when: "not this.stat.exists"
  verifier:
    name: testinfra
    additinonal_file_or-dirs:
       - ../ ../tests/test.py
    options:
       n: 1
    enabled: False
    env:
       F00: bar
    lint:
       name: flake8
       options:
         benchmark: True
       enabled: False
       env:
         F00: bar        

