---
dependency:
  name: galaxy
driver:
  name: docker
  #lint:
  #  name: yamlint        
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default        
verifier:      
  name: testinfra
  lint:
    name: flake8        
